### ISSUE TITLE
Sign-in page

### ISSUE THREAD

**Issue by KostiaLevchenko** [Aurumcopia-DE/aurumcopia-zenhub#161]
AC:
- [x] Use new designs for the sign-in page.
- [x] Add functionality to sign in using email or phone number.

*Desktop designs*: https://xd.adobe.com/view/7146d392-b861-4c35-a074-8d5efc5368d3-2415/
*Mobile designs*: https://xd.adobe.com/view/c8202a73-1e52-4a26-a352-b552f7272c93-9d73/

**Comment by Natali-Oliinyk-qa** [comment]
-  [x] email address is truncated when entered in the email field (WEB / MOB)
![chrome_ejCJMbCd7i.gif](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/275a1770-5fd3-451f-aa07-a7f2045fc37b)![Screenshot_1.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/ad4cab91-e53e-4ca6-8082-5ef4b7853d45)

_________________________________________________________________________

- [x] message about incorrect user password is not displayed
cred   :       noliinyk@dedicatted.com
                  !Qwerty123
I entered the password on the video  :  !Qwerty1

![password.gif](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/735ffbb4-e5a7-4c93-aa8b-0dfa1e4a25e1)
_________________________________________________________________________________
-  [x] with such expansion, the word is moved to the next line

![Screenshot_1.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/defc7a12-24d4-4154-9778-585f81551115)

### **EXPECTED RES**
 ![exoected.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/ddba042e-ca10-4edb-bba6-1e7deb2d2778)

_____________________________________________________________________________________________________
- [x] wrong user email address message is not displayed when the user enters an incorrect email address and a correct password

cred   :       noliinyk@dedicatted.com
                  !Qwerty123
I entered email on the video  :  noliinyk1@dedicatted.com
![encorrect email.gif](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/08dbfa71-4ab0-43af-8fa9-3bbdf25977f6)

- [x] After clicking the "Login" button, an error message should appear if the email and password fields are not filled
![without any data.gif](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/aa02f359-06b2-4914-b74b-f6c09ad9abe2)
_____________________________________________________________________________
- [x] After clicking the "Login" button, an error message (this user is not registered) should appear if the email and password fields are filled with invalid data.

![invalid pass_email.gif](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/043249da-9b10-43ff-9684-12a4dc8cf046)

**Comment by Natali-Oliinyk-qa** [comment]
- [x] the desktop version will be from 1024 to 1920

![123.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/b365a030-b5c9-4d77-b4dc-e44052a27668)

**Comment by Natali-Oliinyk-qa** [comment]
- [x] instead of a field, a frame appears after refreshing the page
![firefox_VQ2mKSG9Qy.gif](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/19f62751-429a-4287-876f-83c088bee9ff)

_________________________________________________

- [x]  the picture does not adapt to the mobile extension
![Screenshot_4.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/b7cc75f9-2476-4120-80f7-96cf6d1dcd59)
______________________________________________________________________
- [x] after entering the e-mail, the user presses the space button - the space does not appear in the field, but an error about the wrong password appears (although the password is correct and the user is redirected to the dashboard page)
![space button.gif](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/02607630-0bc6-43fb-ac32-5ad1b2e17171)
_________________________________________________________________
- [x] error text is superimposed on the other text in that extension if the password is entered incorrectly
![1234.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/26d81e82-cb29-42c5-a241-31d32fab3eb4)
_______________________________________________________________
- [x] "errorsObj.Error" - an error appears after these steps
1.user enters a valid email and an invalid password
2. check "save" and presses  EINLOGGEN button
![firefox_Y050wtoVCh.gif](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/a2413913-d9fd-40dd-a72f-88fcdce2f4b8)

**Comment by Natali-Oliinyk-qa** [comment]
- [x] the picture does not adapt to desktop
![image.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/0b353760-5d37-46d7-a242-7a1b2c36837e)

**Comment by Natali-Oliinyk-qa** [comment]
- [x] message "E-mail address or password is incorrect" should be displayed when, the authorization was unsuccessful (for example, the user with such e-mail address/password is not found in the database, or the password does not match the login and vice versa)

**Comment by Natali-Oliinyk-qa** [comment]
-  [x] the error "Request failed with status code 400" is displayed when the user enters an incorrect password (e.g. !Asd123 i.e. 1 character is missing) and clicks the WEITER button
![sign up.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/b3446ddb-82aa-4626-8553-757509a47393)
