### ISSUE TITLE
Buy gold redirects

### ISSUE THREAD

**Issue by bcmp4p1** [Aurumcopia-DE/aurumcopia-zenhub#199]
- Redirect to first screen buy gold when some value is null

**Comment by Natali-Oliinyk-qa** [comment]
- [X] user has the opportunity to enter a negative amount in the "**Wie viel Euro möchtest du investieren**" field, and the system will redirect the user to the next stage
- [X] In this field, the user has the opportunity to enter the symbols "+" and "-" before the numbers, and system will redirect user to the next stage of the purchase
![chrome_N9dbARNwbP.gif](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/d54bb47c-d403-432f-9e12-11f66c609dc3)

**Comment by Natali-Oliinyk-qa** [comment]
- [X] user enters in the field "Wie viel Euro möchtest du investieren"
symbol - or + (e.g. -100 , +100) and clicks the button WEITER

- ### **EXPECTED  user should redirect to the first screen buy** 
- ###  **ACTUAL user goes to the next screen of buying gold**
![chrome_N9dbARNwbP.gif](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/91eb5ace-987f-44c1-a38f-1745e25c3e72)

**Comment by Natali-Oliinyk-qa** [comment]
@bcmp4p1 the user cannot enter the number 0 (physically he cannot) and this is great, but at the same time he cannot enter the number for example 0.5 (because zero cannot be the first digit), he can enter .5 and already converts it to the next form. 5 to 0.5 ...... It's not ok for user. I have a suggestion that when the user simply puts 0 and clicks on the button, he will be transferred to the initial purchase form, and when there is a dot after zero, then everything is OK
well, so that it would be impossible to enter something like 01233
in general, to prescribe that it only allows if there is a point after zero, and not just (0 or 01234)

**Comment by Natali-Oliinyk-qa** [comment]
- [x] after the dot, the user can enter 3 characters))
![photo_2022-12-07_16-50-48.jpg](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/78e23ff2-1486-4b77-a925-1ad7d2d48355)
